import { 
  BookOpen, 
  Users, 
  GraduationCap, 
  LayoutDashboard, 
  Search, 
  Bell, 
  User, 
  LogOut, 
  ChevronRight, 
  Star, 
  Clock, 
  BarChart, 
  CheckCircle, 
  Award, 
  CreditCard, 
  QrCode, 
  ShieldCheck,
  Plus,
  Settings,
  HelpCircle,
  Mail,
  FileText,
  Menu,
  X,
  Upload,
  ArrowLeft,
  Twitter,
  Github,
  Linkedin,
  ArrowRight,
  Play,
  Eye,
  EyeOff,
  Phone,
  MapPin,
  Code,
  Palette,
  Briefcase,
  Megaphone,
  Heart,
  Globe,
  XCircle
} from 'lucide-react';

export type UserRole = 'admin' | 'instructor' | 'student' | null;

export type View = 
  | 'home'
  | 'login' | 'signup'
  | 'admin-dashboard' | 'admin-students' | 'admin-teachers' | 'admin-courses' | 'admin-course-approvals' | 'admin-teacher-profile' | 'admin-add-course'
  | 'admin-categories' | 'admin-enrollments' | 'admin-quizzes' | 'admin-certificates' | 'admin-payments' | 'admin-reports' | 'admin-settings' | 'admin-teacher-applications'
  | 'instructor-dashboard' | 'create-course' | 'submission-status' | 'edit-course-content' | 'course-analytics' | 'instructor-profile' | 'instructor-messages' | 'instructor-reviews' | 'instructor-quizzes'
  | 'student-dashboard' | 'my-courses' | 'completed-courses' | 'certificates' | 'student-profile' | 'student-settings' | 'course-learning' | 'student-quizzes' | 'student-quiz-session' | 'student-quiz-result'
  | 'browse-courses' | 'categories' | 'course-details' | 'about-us' | 'instructors'
  | 'payment-options' | 'payment-upi' | 'payment-card' | 'payment-success'
  | 'help-center' | 'contact-us' | 'privacy-policy' | 'become-teacher';

export type CourseStatus = 'Pending' | 'Approved' | 'Rejected';

export interface TeacherApplication {
  id: string;
  name: string;
  email: string;
  expertise: string;
  experience: string;
  bio: string;
  status: 'Pending' | 'Approved' | 'Rejected';
  submittedAt: string;
}

export interface Course {
  id: string;
  title: string;
  instructor: string;
  price: number;
  duration: string;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  rating: number;
  students: number;
  image: string;
  category: string;
  description: string;
  status?: CourseStatus;
  rejectionNote?: string;
  progress?: number; // Added progress field
}

export interface Student {
  id: string;
  name: string;
  email: string;
  enrolledCourses: number;
  status: 'Active' | 'Inactive';
}

export interface Teacher {
  id: string;
  name: string;
  email: string;
  assignedCourses: number;
  image: string;
}

export const MOCK_STUDENTS: Student[] = [
  { id: 'S101', name: 'Rahul Verma', email: 'rahul@example.com', enrolledCourses: 3, status: 'Active' },
  { id: 'S102', name: 'Sneha Kapur', email: 'sneha@example.com', enrolledCourses: 5, status: 'Active' },
  { id: 'S103', name: 'Amit Singh', email: 'amit@example.com', enrolledCourses: 2, status: 'Inactive' },
  { id: 'S104', name: 'Pooja Reddy', email: 'pooja@example.com', enrolledCourses: 4, status: 'Active' },
];

export const MOCK_TEACHERS: Teacher[] = [
  { id: 'T201', name: 'Dr. Ananya Iyer', email: 'ananya@lms.com', assignedCourses: 12, image: 'https://picsum.photos/seed/inst1/200/200' },
  { id: 'T202', name: 'Vikram Malhotra', email: 'vikram@lms.com', assignedCourses: 8, image: 'https://picsum.photos/seed/inst2/200/200' },
  { id: 'T203', name: 'Sanya Gupta', email: 'sanya@lms.com', assignedCourses: 15, image: 'https://picsum.photos/seed/inst3/200/200' },
  { id: 'T204', name: 'Arjun Reddy', email: 'arjun@lms.com', assignedCourses: 10, image: 'https://picsum.photos/seed/inst4/200/200' },
  { id: 'T205', name: 'Rohan Sharma', email: 'rohan@lms.com', assignedCourses: 5, image: 'https://picsum.photos/seed/inst5/200/200' },
  { id: 'T206', name: 'Priya Patel', email: 'priya@lms.com', assignedCourses: 7, image: 'https://picsum.photos/seed/inst6/200/200' },
  { id: 'T207', name: 'Karan Singh', email: 'karan@lms.com', assignedCourses: 3, image: 'https://picsum.photos/seed/inst7/200/200' },
  { id: 'T208', name: 'Meera Nair', email: 'meera@lms.com', assignedCourses: 9, image: 'https://picsum.photos/seed/inst8/200/200' },
  { id: 'T209', name: 'Aditya Rao', email: 'aditya@lms.com', assignedCourses: 4, image: 'https://picsum.photos/seed/inst9/200/200' },
  { id: 'T210', name: 'Ishani Bose', email: 'ishani@lms.com', assignedCourses: 6, image: 'https://picsum.photos/seed/inst10/200/200' },
  { id: 'T211', name: 'Varun Joshi', email: 'varun@lms.com', assignedCourses: 2, image: 'https://picsum.photos/seed/inst11/200/200' },
  { id: 'T212', name: 'Kavya Menon', email: 'kavya@lms.com', assignedCourses: 8, image: 'https://picsum.photos/seed/inst12/200/200' },
  { id: 'T213', name: 'Sameer Khan', email: 'sameer@lms.com', assignedCourses: 1, image: 'https://picsum.photos/seed/inst13/200/200' },
  { id: 'T214', name: 'Diya Das', email: 'diya@lms.com', assignedCourses: 11, image: 'https://picsum.photos/seed/inst14/200/200' },
];

export const MOCK_COURSES: Course[] = [
  {
    id: '1',
    title: 'Full Stack Web Development with React & Node.js',
    instructor: 'Arjun Sharma',
    price: 4999,
    duration: '45 Hours',
    level: 'Intermediate',
    rating: 4.8,
    students: 1250,
    image: 'https://picsum.photos/seed/coding/800/600',
    category: 'Development',
    description: 'Master modern web development from scratch. Learn React, Node.js, Express, and MongoDB with real-world projects.',
    progress: 45
  },
  {
    id: '2',
    title: 'Advanced Data Science & Machine Learning',
    instructor: 'Priya Patel',
    price: 5999,
    duration: '60 Hours',
    level: 'Advanced',
    rating: 4.9,
    students: 850,
    image: 'https://picsum.photos/seed/data/800/600',
    category: 'Data Science',
    description: 'Deep dive into machine learning algorithms, neural networks, and big data processing using Python and TensorFlow.',
    progress: 12
  },
  {
    id: '3',
    title: 'UI/UX Design Masterclass: From Figma to Prototype',
    instructor: 'Rohan Verma',
    price: 3499,
    duration: '30 Hours',
    level: 'Beginner',
    rating: 4.7,
    students: 2100,
    image: 'https://picsum.photos/seed/uiux/800/600',
    category: 'Design',
    description: 'Learn the principles of user-centered design. Master Figma and create stunning interfaces that users love.',
    progress: 85
  },
  {
    id: '4',
    title: 'Digital Marketing Strategy & SEO',
    instructor: 'Ananya Iyer',
    price: 2499,
    duration: '25 Hours',
    level: 'Beginner',
    rating: 4.6,
    students: 3200,
    image: 'https://picsum.photos/seed/marketing/800/600',
    category: 'Marketing',
    description: 'Grow your business with effective digital marketing. Learn SEO, SEM, social media marketing, and analytics.'
  },
  {
    id: '5',
    title: 'Financial Analysis & Investment Banking',
    instructor: 'Vikram Malhotra',
    price: 7999,
    duration: '50 Hours',
    level: 'Advanced',
    rating: 4.9,
    students: 450,
    image: 'https://picsum.photos/seed/finance/800/600',
    category: 'Finance',
    description: 'Professional grade financial modeling, valuation techniques, and investment banking fundamentals.'
  },
  {
    id: '6',
    title: 'Python for Data Analysis & Visualization',
    instructor: 'Sanya Gupta',
    price: 3999,
    duration: '35 Hours',
    level: 'Intermediate',
    rating: 4.8,
    students: 1500,
    image: 'https://picsum.photos/seed/python/800/600',
    category: 'Data Science',
    description: 'Learn Python libraries like Pandas, NumPy, and Matplotlib for powerful data analysis and visualization.'
  },
  {
    id: '7',
    title: 'Mobile App Development with Flutter & Dart',
    instructor: 'Arjun Reddy',
    price: 5499,
    duration: '50 Hours',
    level: 'Intermediate',
    rating: 4.9,
    students: 980,
    image: 'https://picsum.photos/seed/mobile/800/600',
    category: 'Development',
    description: 'Build beautiful, natively compiled applications for mobile, web, and desktop from a single codebase.'
  },
  {
    id: '8',
    title: 'Cyber Security Essentials: Zero to Hero',
    instructor: 'Rohan Sharma',
    price: 4499,
    duration: '40 Hours',
    level: 'Beginner',
    rating: 4.7,
    students: 1100,
    image: 'https://picsum.photos/seed/cyber/800/600',
    category: 'IT & Software',
    description: 'Understand the core concepts of cybersecurity, network security, and ethical hacking.'
  },
  {
    id: '9',
    title: 'Cloud Computing with AWS: Certified Solutions Architect',
    instructor: 'Priya Patel',
    price: 6999,
    duration: '55 Hours',
    level: 'Advanced',
    rating: 4.9,
    students: 720,
    image: 'https://picsum.photos/seed/cloud/800/600',
    category: 'IT & Software',
    description: 'Master AWS services and prepare for the Solutions Architect certification with hands-on labs.'
  },
  {
    id: '10',
    title: 'Product Management Fundamentals',
    instructor: 'Karan Singh',
    price: 3299,
    duration: '20 Hours',
    level: 'Beginner',
    rating: 4.6,
    students: 1800,
    image: 'https://picsum.photos/seed/product/800/600',
    category: 'Business',
    description: 'Learn the lifecycle of a product, from ideation to launch, and master the skills of a product manager.'
  },
  {
    id: '11',
    title: 'Graphic Design for Beginners: Adobe Illustrator & Photoshop',
    instructor: 'Meera Nair',
    price: 2999,
    duration: '25 Hours',
    level: 'Beginner',
    rating: 4.7,
    students: 2500,
    image: 'https://picsum.photos/seed/illustrator/800/600',
    category: 'Design',
    description: 'Start your creative journey. Learn the tools and techniques of professional graphic design.'
  },
  {
    id: '12',
    title: 'Content Marketing Strategy & Execution',
    instructor: 'Aditya Rao',
    price: 1999,
    duration: '15 Hours',
    level: 'Beginner',
    rating: 4.5,
    students: 1400,
    image: 'https://picsum.photos/seed/content/800/600',
    category: 'Marketing',
    description: 'Create content that converts. Learn how to build a content strategy that drives business growth.'
  },
  {
    id: '13',
    title: 'Blockchain & Cryptocurrency: A Comprehensive Guide',
    instructor: 'Ishani Bose',
    price: 4999,
    duration: '30 Hours',
    level: 'Intermediate',
    rating: 4.8,
    students: 600,
    image: 'https://picsum.photos/seed/blockchain/800/600',
    category: 'Finance',
    description: 'Understand the technology behind Bitcoin and Ethereum. Learn about smart contracts and decentralized finance.'
  },
  {
    id: '14',
    title: 'Agile Project Management with Scrum',
    instructor: 'Varun Joshi',
    price: 3799,
    duration: '25 Hours',
    level: 'Intermediate',
    rating: 4.7,
    students: 1200,
    image: 'https://picsum.photos/seed/agile/800/600',
    category: 'Business',
    description: 'Master Agile methodologies and the Scrum framework to lead successful projects in any industry.'
  },
  {
    id: '15',
    title: 'Photography Masterclass: From Beginner to Pro',
    instructor: 'Kavya Menon',
    price: 2499,
    duration: '20 Hours',
    level: 'Beginner',
    rating: 4.8,
    students: 3000,
    image: 'https://picsum.photos/seed/camera/800/600',
    category: 'Lifestyle',
    description: 'Learn how to take stunning photos with any camera. Master composition, lighting, and post-processing.'
  },
  {
    id: '16',
    title: 'Machine Learning with Python: Zero to Hero',
    instructor: 'Priya Patel',
    price: 5499,
    duration: '55 Hours',
    level: 'Intermediate',
    rating: 4.8,
    students: 1200,
    image: 'https://picsum.photos/seed/ml/800/600',
    category: 'Data Science',
    description: 'A comprehensive guide to machine learning using Python. Learn regression, classification, clustering, and more.'
  },
  {
    id: '17',
    title: 'Web Design for Everyone: Basics of HTML5 and CSS3',
    instructor: 'Rohan Verma',
    price: 1999,
    duration: '15 Hours',
    level: 'Beginner',
    rating: 4.6,
    students: 4500,
    image: 'https://picsum.photos/seed/webdesign/800/600',
    category: 'Design',
    description: 'Learn the fundamentals of web design. Build your first website using HTML5 and CSS3.'
  },
  {
    id: '18',
    title: 'The Complete Financial Analyst Course 2026',
    instructor: 'Vikram Malhotra',
    price: 4999,
    duration: '40 Hours',
    level: 'Intermediate',
    rating: 4.9,
    students: 1800,
    image: 'https://picsum.photos/seed/analysis/800/600',
    category: 'Finance',
    description: 'Excel, Accounting, Financial Analysis, Business Analysis, and Financial Modeling.'
  },
  {
    id: '19',
    title: 'Social Media Marketing Strategy: Masterclass',
    instructor: 'Ananya Iyer',
    price: 2999,
    duration: '20 Hours',
    level: 'Beginner',
    rating: 4.7,
    students: 2200,
    image: 'https://picsum.photos/seed/social/800/600',
    category: 'Marketing',
    description: 'Master social media marketing on Facebook, Instagram, Twitter, and LinkedIn.'
  },
  {
    id: '20',
    title: 'Java Programming Masterclass for Software Developers',
    instructor: 'Arjun Sharma',
    price: 4499,
    duration: '80 Hours',
    level: 'Intermediate',
    rating: 4.8,
    students: 3500,
    image: 'https://picsum.photos/seed/java/800/600',
    category: 'Development',
    description: 'Learn Java In This Course And Become a Computer Programmer. Java Is One Of The Most In-Demand Programming Languages.',
    progress: 30
  },
  {
    id: '21',
    title: 'Deep Learning Specialization with Keras & PyTorch',
    instructor: 'Sanya Gupta',
    price: 6499,
    duration: '70 Hours',
    level: 'Advanced',
    rating: 4.9,
    students: 500,
    image: 'https://picsum.photos/seed/deeplearning/800/600',
    category: 'Data Science',
    description: 'Master Deep Learning, and Break into AI. Learn how to build neural networks and deploy them.'
  },
  {
    id: '22',
    title: 'Logo Design Masterclass: Learn Logo Design',
    instructor: 'Meera Nair',
    price: 2499,
    duration: '15 Hours',
    level: 'Beginner',
    rating: 4.7,
    students: 1500,
    image: 'https://picsum.photos/seed/logo/800/600',
    category: 'Design',
    description: 'Learn the principles of logo design. Create stunning logos that stand out.'
  },
  {
    id: '23',
    title: 'The Complete Digital Marketing Course - 12 Courses in 1',
    instructor: 'Aditya Rao',
    price: 3999,
    duration: '25 Hours',
    level: 'Beginner',
    rating: 4.6,
    students: 5000,
    image: 'https://picsum.photos/seed/digital/800/600',
    category: 'Marketing',
    description: 'Master Digital Marketing Strategy, Social Media Marketing, SEO, YouTube, Email, Facebook Marketing, Analytics and More!'
  },
  {
    id: '24',
    title: 'Stock Market Investing for Beginners',
    instructor: 'Ishani Bose',
    price: 3499,
    duration: '12 Hours',
    level: 'Beginner',
    rating: 4.8,
    students: 4000,
    image: 'https://picsum.photos/seed/stock/800/600',
    category: 'Finance',
    description: 'Learn how to invest in the stock market. Understand technical and fundamental analysis.'
  },
  {
    id: '25',
    title: 'The Complete SQL Bootcamp: Go from Zero to Hero',
    instructor: 'Varun Joshi',
    price: 2999,
    duration: '10 Hours',
    level: 'Beginner',
    rating: 4.7,
    students: 6000,
    image: 'https://picsum.photos/seed/sql/800/600',
    category: 'Development',
    description: 'Become an expert at SQL! Learn how to query databases and perform data analysis.'
  },
  {
    id: '26',
    title: 'Photography Masterclass: A Complete Guide to Photography',
    instructor: 'Kavya Menon',
    price: 2499,
    duration: '25 Hours',
    level: 'Beginner',
    rating: 4.8,
    students: 3500,
    image: 'https://picsum.photos/seed/photography/800/600',
    category: 'Lifestyle',
    description: 'The best-selling online photography course that teaches you how to take amazing images and even sell them.'
  },
  {
    id: '27',
    title: 'The Complete 2026 Web Development Bootcamp',
    instructor: 'Arjun Sharma',
    price: 4999,
    duration: '65 Hours',
    level: 'Beginner',
    rating: 4.9,
    students: 10000,
    image: 'https://picsum.photos/seed/webbootcamp/800/600',
    category: 'Development',
    description: 'Become a Full-Stack Web Developer with just ONE course. HTML, CSS, Javascript, Node, React, MongoDB, Web3 and DApps.'
  },
  {
    id: '28',
    title: 'Data Science A-Z: Real-Life Data Science Exercises Included',
    instructor: 'Priya Patel',
    price: 5999,
    duration: '20 Hours',
    level: 'Intermediate',
    rating: 4.7,
    students: 2500,
    image: 'https://picsum.photos/seed/datascience/800/600',
    category: 'Data Science',
    description: 'Learn Data Science step by step through real-life examples. Data Mining, Modeling, Tableau Visualization and more!'
  },
  {
    id: '29',
    title: 'User Experience Design Essentials - Adobe XD UI UX Design',
    instructor: 'Rohan Verma',
    price: 3499,
    duration: '15 Hours',
    level: 'Beginner',
    rating: 4.8,
    students: 3000,
    image: 'https://picsum.photos/seed/uxdesign/800/600',
    category: 'Design',
    description: 'Use Adobe XD to create a professional UX design from scratch. Learn the principles of user experience.'
  },
  {
    id: '30',
    title: 'The Complete Investment Banking Course 2026',
    instructor: 'Vikram Malhotra',
    price: 7999,
    duration: '15 Hours',
    level: 'Advanced',
    rating: 4.9,
    students: 800,
    image: 'https://picsum.photos/seed/investing/800/600',
    category: 'Finance',
    description: 'The most comprehensive course on investment banking. Learn valuation, M&A, LBO, and more.'
  },
  {
    id: '31',
    title: 'SEO 2026: Complete SEO Training + SEO for WordPress Websites',
    instructor: 'Ananya Iyer',
    price: 2499,
    duration: '10 Hours',
    level: 'Beginner',
    rating: 4.6,
    students: 4000,
    image: 'https://picsum.photos/seed/seo/800/600',
    category: 'Marketing',
    description: 'Master SEO and get more traffic to your website. Learn keyword research, on-page SEO, and link building.'
  },
  {
    id: '32',
    title: 'The Complete Python Bootcamp From Zero to Hero in Python',
    instructor: 'Sanya Gupta',
    price: 3999,
    duration: '22 Hours',
    level: 'Beginner',
    rating: 4.8,
    students: 15000,
    image: 'https://picsum.photos/seed/pythondev/800/600',
    category: 'Development',
    description: 'Learn Python like a Professional Start from the basics and go all the way to creating your own applications and games.'
  },
  {
    id: '33',
    title: 'Graphic Design Masterclass - Learn GREAT Design',
    instructor: 'Meera Nair',
    price: 2999,
    duration: '20 Hours',
    level: 'Beginner',
    rating: 4.7,
    students: 2800,
    image: 'https://picsum.photos/seed/graphic/800/600',
    category: 'Design',
    description: 'The Ultimate Graphic Design Course - Learn Typography, Color Theory, Layout Design, Branding and more.'
  },
  {
    id: '34',
    title: 'Facebook Ads & Facebook Marketing MASTERY 2026',
    instructor: 'Aditya Rao',
    price: 3499,
    duration: '12 Hours',
    level: 'Intermediate',
    rating: 4.8,
    students: 3200,
    image: 'https://picsum.photos/seed/facebook/800/600',
    category: 'Marketing',
    description: 'Master Facebook Ads and grow your business. Learn how to create effective ad campaigns and target the right audience.'
  },
  {
    id: '35',
    title: 'Cryptocurrency Investment Course 2026: Fund your Retirement!',
    instructor: 'Ishani Bose',
    price: 4999,
    duration: '15 Hours',
    level: 'Intermediate',
    rating: 4.9,
    students: 1200,
    image: 'https://picsum.photos/seed/crypto/800/600',
    category: 'Finance',
    description: 'Learn how to invest in cryptocurrencies. Understand the risks and rewards of the crypto market.'
  },
  {
    id: '36',
    title: 'The Complete Node.js Developer Course (3rd Edition)',
    instructor: 'Arjun Sharma',
    price: 4499,
    duration: '35 Hours',
    level: 'Intermediate',
    rating: 4.8,
    students: 4500,
    image: 'https://picsum.photos/seed/node/800/600',
    category: 'Development',
    description: 'Learn Node.js by building real-world applications with Node, Express, MongoDB, Jest, and more!'
  },
  {
    id: '37',
    title: 'Tableau 2026 A-Z: Hands-On Tableau Training for Data Science',
    instructor: 'Priya Patel',
    price: 3999,
    duration: '10 Hours',
    level: 'Beginner',
    rating: 4.7,
    students: 3000,
    image: 'https://picsum.photos/seed/tableau/800/600',
    category: 'Data Science',
    description: 'Learn Tableau for Data Science step-by-step. Real-Life Data Analytics Exercises & Quizzes Included. Learn by doing!'
  },
  {
    id: '38',
    title: 'Adobe Premiere Pro CC Masterclass: Video Editing in Premiere',
    instructor: 'Kavya Menon',
    price: 3499,
    duration: '12 Hours',
    level: 'Beginner',
    rating: 4.8,
    students: 2500,
    image: 'https://picsum.photos/seed/videoediting/800/600',
    category: 'Design',
    description: 'Learn how to edit videos in Adobe Premiere Pro with these easy-to-follow video editing tutorials.'
  },
  {
    id: '39',
    title: 'The Complete Financial Management Course',
    instructor: 'Vikram Malhotra',
    price: 4999,
    duration: '20 Hours',
    level: 'Intermediate',
    rating: 4.7,
    students: 1500,
    image: 'https://picsum.photos/seed/fin6/800/600',
    category: 'Finance',
    description: 'Learn financial management from scratch. Understand financial statements, budgeting, and more.'
  },
  {
    id: '40',
    title: 'Instagram Marketing 2026: Complete Guide To Instagram Growth',
    instructor: 'Ananya Iyer',
    price: 2499,
    duration: '8 Hours',
    level: 'Beginner',
    rating: 4.6,
    students: 3500,
    image: 'https://picsum.photos/seed/mkt6/800/600',
    category: 'Marketing',
    description: 'Master Instagram marketing and grow your following. Learn how to create engaging content and use hashtags.'
  },
  {
    id: '41',
    title: 'The Complete C# Masterclass',
    instructor: 'Arjun Sharma',
    price: 4499,
    duration: '40 Hours',
    level: 'Intermediate',
    rating: 4.8,
    students: 2000,
    image: 'https://picsum.photos/seed/dev7/800/600',
    category: 'Development',
    description: 'Learn C# by building real-world applications. Master the fundamentals of object-oriented programming.'
  },
  {
    id: '42',
    title: 'R Programming A-Z™: R For Data Science With Real Exercises!',
    instructor: 'Priya Patel',
    price: 3999,
    duration: '10 Hours',
    level: 'Beginner',
    rating: 4.7,
    students: 1800,
    image: 'https://picsum.photos/seed/ds7/800/600',
    category: 'Data Science',
    description: 'Learn Programming In R And R Studio. Data Analytics, Data Science, Statistical Analysis, Packages, Functions, GGPlot2.'
  },
  {
    id: '43',
    title: 'After Effects CC: The Complete Motion Graphics Masterclass',
    instructor: 'Meera Nair',
    price: 3499,
    duration: '15 Hours',
    level: 'Intermediate',
    rating: 4.8,
    students: 1200,
    image: 'https://picsum.photos/seed/design7/800/600',
    category: 'Design',
    description: 'Learn how to create motion graphics in Adobe After Effects. Master the tools and techniques of motion design.'
  },
  {
    id: '44',
    title: 'The Complete Business Plan Course',
    instructor: 'Karan Singh',
    price: 3299,
    duration: '10 Hours',
    level: 'Beginner',
    rating: 4.7,
    students: 2200,
    image: 'https://picsum.photos/seed/biz3/800/600',
    category: 'Business',
    description: 'Learn how to write a professional business plan. Understand the key components of a successful plan.'
  },
  {
    id: '45',
    title: 'Google Ads Masterclass 2026: Profit with Pay Per Click',
    instructor: 'Aditya Rao',
    price: 3499,
    duration: '12 Hours',
    level: 'Intermediate',
    rating: 4.8,
    students: 2800,
    image: 'https://picsum.photos/seed/mkt7/800/600',
    category: 'Marketing',
    description: 'Master Google Ads and grow your business. Learn how to create effective PPC campaigns and target the right keywords.'
  },
  {
    id: '46',
    title: 'The Complete Personal Finance Course: Save, Protect, Make Money',
    instructor: 'Ishani Bose',
    price: 2999,
    duration: '15 Hours',
    level: 'Beginner',
    rating: 4.9,
    students: 5000,
    image: 'https://picsum.photos/seed/fin7/800/600',
    category: 'Finance',
    description: 'Learn how to manage your personal finances. Understand how to save, invest, and protect your money.'
  },
  {
    id: '47',
    title: 'The Complete React Native + Hooks Course',
    instructor: 'Arjun Sharma',
    price: 4999,
    duration: '40 Hours',
    level: 'Intermediate',
    rating: 4.9,
    students: 3500,
    image: 'https://picsum.photos/seed/dev8/800/600',
    category: 'Development',
    description: 'Understand React Native with Hooks, including Navigation, Firebase, and Redux.'
  },
  {
    id: '48',
    title: 'Statistics for Data Science and Business Analysis',
    instructor: 'Priya Patel',
    price: 3999,
    duration: '10 Hours',
    level: 'Beginner',
    rating: 4.7,
    students: 4000,
    image: 'https://picsum.photos/seed/ds8/800/600',
    category: 'Data Science',
    description: 'Statistics you need in the office: Descriptive & Inferential statistics, Hypothesis testing, Regression analysis.'
  },
  {
    id: '49',
    title: 'Drawing Masterclass: From Beginner to Advanced',
    instructor: 'Meera Nair',
    price: 2499,
    duration: '20 Hours',
    level: 'Beginner',
    rating: 4.8,
    students: 2000,
    image: 'https://picsum.photos/seed/life2/800/600',
    category: 'Lifestyle',
    description: 'Learn how to draw from scratch. Master the tools and techniques of professional drawing.'
  },
  {
    id: '50',
    title: 'The Complete Management Skills Course',
    instructor: 'Karan Singh',
    price: 3799,
    duration: '15 Hours',
    level: 'Intermediate',
    rating: 4.7,
    students: 1500,
    image: 'https://picsum.photos/seed/biz4/800/600',
    category: 'Business',
    description: 'Learn the essential management skills. Understand how to lead teams and manage projects effectively.'
  },
  {
    id: '51',
    title: 'YouTube Marketing 2026: Complete Guide To YouTube Growth',
    instructor: 'Aditya Rao',
    price: 2499,
    duration: '10 Hours',
    level: 'Beginner',
    rating: 4.6,
    students: 3000,
    image: 'https://picsum.photos/seed/mkt8/800/600',
    category: 'Marketing',
    description: 'Master YouTube marketing and grow your channel. Learn how to create engaging videos and use tags.'
  },
  {
    id: '52',
    title: 'The Complete Options Trading Course',
    instructor: 'Ishani Bose',
    price: 4999,
    duration: '15 Hours',
    level: 'Advanced',
    rating: 4.9,
    students: 1000,
    image: 'https://picsum.photos/seed/fin8/800/600',
    category: 'Finance',
    description: 'Learn how to trade options. Understand the risks and rewards of the options market.'
  },
  {
    id: '53',
    title: 'The Complete Angular Course: Go from Zero to Hero',
    instructor: 'Arjun Sharma',
    price: 4499,
    duration: '45 Hours',
    level: 'Intermediate',
    rating: 4.8,
    students: 2500,
    image: 'https://picsum.photos/seed/dev9/800/600',
    category: 'Development',
    description: 'Master Angular and build real-world applications. Understand the fundamentals of Angular development.'
  },
  {
    id: '54',
    title: 'Deep Learning with Python and Keras',
    instructor: 'Priya Patel',
    price: 5999,
    duration: '20 Hours',
    level: 'Advanced',
    rating: 4.9,
    students: 600,
    image: 'https://picsum.photos/seed/ds9/800/600',
    category: 'Data Science',
    description: 'Learn deep learning with Python and Keras. Master the tools and techniques of deep learning.'
  },
  {
    id: '55',
    title: 'Character Design Masterclass: From Beginner to Advanced',
    instructor: 'Meera Nair',
    price: 2999,
    duration: '20 Hours',
    level: 'Beginner',
    rating: 4.8,
    students: 1500,
    image: 'https://picsum.photos/seed/design8/800/600',
    category: 'Design',
    description: 'Learn how to design characters from scratch. Master the tools and techniques of character design.'
  },
  {
    id: '56',
    title: 'The Complete Sales Skills Course',
    instructor: 'Karan Singh',
    price: 3299,
    duration: '10 Hours',
    level: 'Beginner',
    rating: 4.7,
    students: 2000,
    image: 'https://picsum.photos/seed/biz5/800/600',
    category: 'Business',
    description: 'Learn the essential sales skills. Understand how to close deals and manage sales teams effectively.'
  },
  {
    id: '57',
    title: 'Email Marketing Masterclass 2026: Grow Your Business',
    instructor: 'Aditya Rao',
    price: 2499,
    duration: '8 Hours',
    level: 'Beginner',
    rating: 4.6,
    students: 2500,
    image: 'https://picsum.photos/seed/mkt9/800/600',
    category: 'Marketing',
    description: 'Master email marketing and grow your business. Learn how to create effective email campaigns and target the right audience.'
  },
  {
    id: '58',
    title: 'The Complete Real Estate Investing Course',
    instructor: 'Ishani Bose',
    price: 4999,
    duration: '15 Hours',
    level: 'Intermediate',
    rating: 4.9,
    students: 1200,
    image: 'https://picsum.photos/seed/fin9/800/600',
    category: 'Finance',
    description: 'Learn how to invest in real estate. Understand the risks and rewards of the real estate market.'
  },
  {
    id: '59',
    title: 'The Complete Vue.js Course: Go from Zero to Hero',
    instructor: 'Arjun Sharma',
    price: 4499,
    duration: '35 Hours',
    level: 'Intermediate',
    rating: 4.8,
    students: 1800,
    image: 'https://picsum.photos/seed/dev10/800/600',
    category: 'Development',
    description: 'Master Vue.js and build real-world applications. Understand the fundamentals of Vue.js development.'
  },
  {
    id: '60',
    title: 'Natural Language Processing with Python',
    instructor: 'Priya Patel',
    price: 5999,
    duration: '20 Hours',
    level: 'Advanced',
    rating: 4.9,
    students: 500,
    image: 'https://picsum.photos/seed/ds10/800/600',
    category: 'Data Science',
    description: 'Learn natural language processing with Python. Master the tools and techniques of NLP.'
  },
  {
    id: '61',
    title: 'Illustration Masterclass: From Beginner to Advanced',
    instructor: 'Meera Nair',
    price: 2999,
    duration: '20 Hours',
    level: 'Beginner',
    rating: 4.8,
    students: 1200,
    image: 'https://picsum.photos/seed/design9/800/600',
    category: 'Design',
    description: 'Learn how to illustrate from scratch. Master the tools and techniques of professional illustration.'
  },
  {
    id: '62',
    title: 'The Complete Leadership Skills Course',
    instructor: 'Karan Singh',
    price: 3799,
    duration: '15 Hours',
    level: 'Intermediate',
    rating: 4.7,
    students: 1500,
    image: 'https://picsum.photos/seed/biz6/800/600',
    category: 'Business',
    description: 'Learn the essential leadership skills. Understand how to lead teams and manage projects effectively.'
  },
  {
    id: '63',
    title: 'Affiliate Marketing Masterclass 2026: Grow Your Business',
    instructor: 'Aditya Rao',
    price: 2499,
    duration: '10 Hours',
    level: 'Beginner',
    rating: 4.6,
    students: 2000,
    image: 'https://picsum.photos/seed/mkt10/800/600',
    category: 'Marketing',
    description: 'Master affiliate marketing and grow your business. Learn how to create effective affiliate campaigns and target the right audience.'
  },
  {
    id: '64',
    title: 'The Complete Tax Planning Course',
    instructor: 'Ishani Bose',
    price: 4999,
    duration: '15 Hours',
    level: 'Intermediate',
    rating: 4.9,
    students: 800,
    image: 'https://picsum.photos/seed/fin10/800/600',
    category: 'Finance',
    description: 'Learn how to plan your taxes. Understand the key components of a successful tax plan.'
  },
  {
    id: '65',
    title: 'The Complete Docker & Kubernetes Course',
    instructor: 'Arjun Sharma',
    price: 4499,
    duration: '40 Hours',
    level: 'Intermediate',
    rating: 4.9,
    students: 2200,
    image: 'https://picsum.photos/seed/dev11/800/600',
    category: 'Development',
    description: 'Master Docker and Kubernetes and build real-world applications. Understand the fundamentals of containerization.'
  },
  {
    id: '66',
    title: 'Nutrition Masterclass: Build Your Perfect Diet',
    instructor: 'Dr. Ananya Iyer',
    price: 2999,
    duration: '15 Hours',
    level: 'Beginner',
    rating: 4.8,
    students: 1200,
    image: 'https://picsum.photos/seed/health1/800/600',
    category: 'Health',
    description: 'Learn the science of nutrition and how to create a sustainable, healthy diet for your lifestyle.'
  },
  {
    id: '67',
    title: 'Yoga for Beginners: 30 Days to Flexibility',
    instructor: 'Kavya Menon',
    price: 1999,
    duration: '20 Hours',
    level: 'Beginner',
    rating: 4.9,
    students: 3500,
    image: 'https://picsum.photos/seed/health2/800/600',
    category: 'Health',
    description: 'A step-by-step guide to yoga. Improve your flexibility, strength, and mental clarity.'
  },
  {
    id: '68',
    title: 'Mental Health & Mindfulness: Stress Management',
    instructor: 'Meera Nair',
    price: 2499,
    duration: '12 Hours',
    level: 'Beginner',
    rating: 4.7,
    students: 2800,
    image: 'https://picsum.photos/seed/health3/800/600',
    category: 'Health',
    description: 'Practical techniques for managing stress, anxiety, and improving your overall mental well-being.'
  },
  {
    id: '69',
    title: 'Fitness Foundations: Strength Training 101',
    instructor: 'Arjun Reddy',
    price: 3499,
    duration: '25 Hours',
    level: 'Beginner',
    rating: 4.8,
    students: 1500,
    image: 'https://picsum.photos/seed/health4/800/600',
    category: 'Health',
    description: 'Master the fundamentals of strength training. Learn proper form and build an effective workout routine.'
  },
  {
    id: '70',
    title: 'Holistic Wellness: A Guide to Natural Living',
    instructor: 'Sanya Gupta',
    price: 2799,
    duration: '18 Hours',
    level: 'Intermediate',
    rating: 4.6,
    students: 900,
    image: 'https://picsum.photos/seed/health5/800/600',
    category: 'Health',
    description: 'Explore holistic health practices, from herbal remedies to sustainable living habits.'
  },
  {
    id: '71',
    title: 'Generative AI & LLM Engineering',
    instructor: 'Priya Patel',
    price: 8999,
    duration: '40 Hours',
    level: 'Advanced',
    rating: 4.9,
    students: 1500,
    image: 'https://picsum.photos/seed/ai/800/600',
    category: 'Artificial Intelligence',
    description: 'Master the art of building applications with Large Language Models. Learn prompt engineering, fine-tuning, and RAG.'
  },
  {
    id: '72',
    title: 'Advanced Ethical Hacking & Penetration Testing',
    instructor: 'Rohan Sharma',
    price: 6499,
    duration: '55 Hours',
    level: 'Advanced',
    rating: 4.8,
    students: 800,
    image: 'https://picsum.photos/seed/hacking/800/600',
    category: 'IT & Software',
    description: 'Go beyond the basics. Learn advanced exploitation techniques, network pivoting, and red teaming strategies.'
  },
  {
    id: '73',
    title: 'Strategic Product Management Masterclass',
    instructor: 'Karan Singh',
    price: 4999,
    duration: '30 Hours',
    level: 'Intermediate',
    rating: 4.7,
    students: 1200,
    image: 'https://picsum.photos/seed/strategy/800/600',
    category: 'Business',
    description: 'Learn how to define product vision, strategy, and roadmap. Master stakeholder management and data-driven decision making.'
  },
  {
    id: '74',
    title: 'Advanced Motion Graphics with After Effects',
    instructor: 'Meera Nair',
    price: 4499,
    duration: '35 Hours',
    level: 'Advanced',
    rating: 4.9,
    students: 600,
    image: 'https://picsum.photos/seed/motion/800/600',
    category: 'Design',
    description: 'Create complex animations and visual effects. Master expressions, 3D space, and advanced compositing in After Effects.'
  },
  {
    id: '75',
    title: 'Performance Marketing & Growth Hacking',
    instructor: 'Aditya Rao',
    price: 3999,
    duration: '25 Hours',
    level: 'Intermediate',
    rating: 4.7,
    students: 1800,
    image: 'https://picsum.photos/seed/growth/800/600',
    category: 'Marketing',
    description: 'Drive exponential growth using data-backed marketing strategies. Master paid acquisition, A/B testing, and conversion optimization.'
  },
  {
    id: '76',
    title: 'Advanced Financial Modeling for M&A',
    instructor: 'Vikram Malhotra',
    price: 9999,
    duration: '45 Hours',
    level: 'Advanced',
    rating: 4.9,
    students: 350,
    image: 'https://picsum.photos/seed/merger/800/600',
    category: 'Finance',
    description: 'Build complex financial models for mergers and acquisitions. Master valuation, synergy analysis, and deal structuring.'
  },
  {
    id: '77',
    title: 'Ethereum Smart Contract Development with Solidity',
    instructor: 'Ishani Bose',
    price: 7499,
    duration: '50 Hours',
    level: 'Advanced',
    rating: 4.8,
    students: 500,
    image: 'https://picsum.photos/seed/solidity/800/600',
    category: 'Development',
    description: 'Learn how to write secure and efficient smart contracts. Master Solidity, Hardhat, and decentralized application architecture.'
  },
  {
    id: '78',
    title: 'iOS App Development with Swift & SwiftUI',
    instructor: 'Arjun Reddy',
    price: 6999,
    duration: '60 Hours',
    level: 'Advanced',
    rating: 4.9,
    students: 750,
    image: 'https://picsum.photos/seed/swift/800/600',
    category: 'Development',
    description: 'Build professional iOS applications. Master Swift, SwiftUI, Combine, and modern iOS architecture patterns.'
  },
  {
    id: '79',
    title: 'Data Storytelling & Interactive Visualization',
    instructor: 'Sanya Gupta',
    price: 4299,
    duration: '28 Hours',
    level: 'Intermediate',
    rating: 4.7,
    students: 1100,
    image: 'https://picsum.photos/seed/storytelling/800/600',
    category: 'Data Science',
    description: 'Learn how to communicate insights effectively. Master D3.js, Tableau, and the art of narrative data visualization.'
  },
  {
    id: '80',
    title: 'Cloud Native Architecture & Microservices',
    instructor: 'Arjun Sharma',
    price: 7999,
    duration: '50 Hours',
    level: 'Advanced',
    rating: 4.9,
    students: 650,
    image: 'https://picsum.photos/seed/microservices/800/600',
    category: 'IT & Software',
    description: 'Design scalable and resilient cloud systems. Master microservices patterns, service mesh, and serverless architectures.'
  },
  {
    id: 'dev-python',
    title: 'Python Programming Masterclass',
    instructor: 'Vikram Malhotra',
    price: 3999,
    duration: '40 Hours',
    level: 'Beginner',
    rating: 4.9,
    students: 2500,
    image: 'https://picsum.photos/seed/python/800/600',
    category: 'Development',
    description: 'Learn Python from scratch. Cover basics to advanced topics like decorators and generators.'
  },
  {
    id: 'dev-react',
    title: 'React.js Masterclass',
    instructor: 'Arjun Sharma',
    price: 4499,
    duration: '35 Hours',
    level: 'Intermediate',
    rating: 4.8,
    students: 1800,
    image: 'https://picsum.photos/seed/react/800/600',
    category: 'Development',
    description: 'Master React.js with hooks, context API, and performance optimization techniques.'
  },
  {
    id: 'dev-java',
    title: 'Java Backend Development',
    instructor: 'Sanya Gupta',
    price: 5499,
    duration: '50 Hours',
    level: 'Advanced',
    rating: 4.7,
    students: 900,
    image: 'https://picsum.photos/seed/java/800/600',
    category: 'Development',
    description: 'Build robust backends with Java, Spring Boot, and Hibernate.'
  },
  {
    id: 'dev-ml',
    title: 'Machine Learning Fundamentals',
    instructor: 'Priya Patel',
    price: 5999,
    duration: '55 Hours',
    level: 'Advanced',
    rating: 4.9,
    students: 750,
    image: 'https://picsum.photos/seed/ml/800/600',
    category: 'Development',
    description: 'Understand the math and algorithms behind machine learning using Python.'
  },
  {
    id: 'des-bootcamp',
    title: 'UI/UX Design Bootcamp',
    instructor: 'Rohan Verma',
    price: 3499,
    duration: '30 Hours',
    level: 'Beginner',
    rating: 4.7,
    students: 2100,
    image: 'https://picsum.photos/seed/uiux/800/600',
    category: 'Design',
    description: 'Learn the principles of user-centered design. Master Figma and create stunning interfaces.'
  },
  {
    id: 'des-figma',
    title: 'Figma for Beginners',
    instructor: 'Rohan Verma',
    price: 1999,
    duration: '15 Hours',
    level: 'Beginner',
    rating: 4.6,
    students: 3500,
    image: 'https://picsum.photos/seed/figma/800/600',
    category: 'Design',
    description: 'Master Figma for UI design. Learn components, auto-layout, and prototyping.'
  },
  {
    id: 'des-graphic',
    title: 'Graphic Design Masterclass',
    instructor: 'Meera Nair',
    price: 2999,
    duration: '25 Hours',
    level: 'Beginner',
    rating: 4.7,
    students: 2500,
    image: 'https://picsum.photos/seed/graphic/800/600',
    category: 'Design',
    description: 'Learn Adobe Illustrator and Photoshop for professional graphic design.'
  },
  {
    id: 'des-motion',
    title: 'Motion Graphics with After Effects',
    instructor: 'Meera Nair',
    price: 3499,
    duration: '20 Hours',
    level: 'Intermediate',
    rating: 4.8,
    students: 1200,
    image: 'https://picsum.photos/seed/motion/800/600',
    category: 'Design',
    description: 'Create stunning animations and visual effects with Adobe After Effects.'
  },
  {
    id: 'biz-startup',
    title: 'Entrepreneurship: Launch Your Startup',
    instructor: 'Karan Singh',
    price: 3299,
    duration: '20 Hours',
    level: 'Beginner',
    rating: 4.6,
    students: 1800,
    image: 'https://picsum.photos/seed/startup/800/600',
    category: 'Business',
    description: 'Learn how to build a startup from ideation to launch.'
  },
  {
    id: 'biz-strategy',
    title: 'Business Strategy Masterclass',
    instructor: 'Varun Joshi',
    price: 3799,
    duration: '25 Hours',
    level: 'Intermediate',
    rating: 4.7,
    students: 1200,
    image: 'https://picsum.photos/seed/strategy/800/600',
    category: 'Business',
    description: 'Master strategic thinking and competitive analysis.'
  },
  {
    id: 'biz-leadership',
    title: 'Leadership & Management',
    instructor: 'Karan Singh',
    price: 3999,
    duration: '15 Hours',
    level: 'Intermediate',
    rating: 4.8,
    students: 1500,
    image: 'https://picsum.photos/seed/leadership/800/600',
    category: 'Business',
    description: 'Develop essential leadership skills to manage teams effectively.'
  },
  {
    id: 'mkt-mastery',
    title: 'Digital Marketing Mastery',
    instructor: 'Ananya Iyer',
    price: 2499,
    duration: '25 Hours',
    level: 'Beginner',
    rating: 4.6,
    students: 3200,
    image: 'https://picsum.photos/seed/marketing/800/600',
    category: 'Marketing',
    description: 'Learn SEO, SEM, social media marketing, and analytics.'
  },
  {
    id: 'mkt-seo',
    title: 'SEO Mastery',
    instructor: 'Ananya Iyer',
    price: 1999,
    duration: '15 Hours',
    level: 'Intermediate',
    rating: 4.7,
    students: 2200,
    image: 'https://picsum.photos/seed/seo/800/600',
    category: 'Marketing',
    description: 'Master search engine optimization and drive organic traffic.'
  },
  {
    id: 'mkt-social',
    title: 'Social Media Marketing',
    instructor: 'Aditya Rao',
    price: 2999,
    duration: '20 Hours',
    level: 'Beginner',
    rating: 4.7,
    students: 2800,
    image: 'https://picsum.photos/seed/social/800/600',
    category: 'Marketing',
    description: 'Build a strong brand presence on social media platforms.'
  },
  {
    id: 'fin-modeling',
    title: 'Financial Analysis & Modeling',
    instructor: 'Vikram Malhotra',
    price: 7999,
    duration: '50 Hours',
    level: 'Advanced',
    rating: 4.9,
    students: 450,
    image: 'https://picsum.photos/seed/finance/800/600',
    category: 'Finance',
    description: 'Professional grade financial modeling and valuation techniques.'
  },
  {
    id: 'fin-invest',
    title: 'Investment Strategies',
    instructor: 'Ishani Bose',
    price: 4999,
    duration: '30 Hours',
    level: 'Intermediate',
    rating: 4.8,
    students: 600,
    image: 'https://picsum.photos/seed/invest/800/600',
    category: 'Finance',
    description: 'Learn how to build a diversified investment portfolio.'
  },
  {
    id: 'fin-crypto',
    title: 'Cryptocurrency Basics',
    instructor: 'Ishani Bose',
    price: 3499,
    duration: '12 Hours',
    level: 'Beginner',
    rating: 4.8,
    students: 4000,
    image: 'https://picsum.photos/seed/crypto/800/600',
    category: 'Finance',
    description: 'Understand blockchain and how to trade cryptocurrencies.'
  },
  {
    id: 'hlth-nutrition',
    title: 'Nutrition Fundamentals',
    instructor: 'Kavya Menon',
    price: 1999,
    duration: '15 Hours',
    level: 'Beginner',
    rating: 4.7,
    students: 1800,
    image: 'https://picsum.photos/seed/nutrition/800/600',
    category: 'Health',
    description: 'Learn the basics of healthy eating and nutrition science.'
  },
  {
    id: 'hlth-mental',
    title: 'Mental Health Awareness',
    instructor: 'Kavya Menon',
    price: 1499,
    duration: '10 Hours',
    level: 'Beginner',
    rating: 4.9,
    students: 2200,
    image: 'https://picsum.photos/seed/mental/800/600',
    category: 'Health',
    description: 'Understand mental health and learn coping strategies.'
  },
  {
    id: 'hlth-yoga',
    title: 'Yoga & Wellness',
    instructor: 'Kavya Menon',
    price: 2499,
    duration: '20 Hours',
    level: 'Beginner',
    rating: 4.8,
    students: 3000,
    image: 'https://picsum.photos/seed/yoga/800/600',
    category: 'Health',
    description: 'Improve your physical and mental well-being with yoga.'
  }
];

export const ICONS = {
  BookOpen,
  Users,
  GraduationCap,
  LayoutDashboard,
  Search,
  Bell,
  User,
  LogOut,
  ChevronRight,
  Star,
  Clock,
  BarChart,
  CheckCircle,
  Award,
  CreditCard,
  QrCode,
  ShieldCheck,
  Plus,
  Settings,
  HelpCircle,
  Mail,
  FileText,
  Menu,
  X,
  Upload,
  ArrowLeft,
  Twitter,
  Github,
  Linkedin,
  ArrowRight,
  Play,
  Eye,
  EyeOff,
  Phone,
  MapPin,
  Code,
  Palette,
  Briefcase,
  Megaphone,
  Heart,
  Globe,
  XCircle
};
